#!/usr/bin/env bash
set -e

git clone https://aur.archlinux.org/yay.git

cd yay
makepkg -si
cd ..
yay --needed -S `cat pkg`

sudo systemctl enable NetworkManager
sudo systemctl start NetworkManager

sudo systemctl enable bluetooth
sudo systemctl start bluetooth

sudo systemctl enable ufw
sudo systemctl start ufw
sudo ufw enable

sudo cp touchpad/40-libinput.conf /etc/X11/xorg.conf.d/
